# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Password.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PasswordWindow(object):
    def setupUi(self, PasswordWindow):
        PasswordWindow.setObjectName("PasswordWindow")
        PasswordWindow.resize(513, 166)
        self.centralwidget = QtWidgets.QWidget(PasswordWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PasswordLabel = QtWidgets.QLabel(self.centralwidget)
        self.PasswordLabel.setGeometry(QtCore.QRect(160, 10, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.PasswordLabel.setFont(font)
        self.PasswordLabel.setObjectName("PasswordLabel")
        self.Enter_password = QtWidgets.QPushButton(self.centralwidget)
        self.Enter_password.setGeometry(QtCore.QRect(360, 70, 101, 41))
        self.Enter_password.setObjectName("Enter_password")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 80, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.password_blank = QtWidgets.QLineEdit(self.centralwidget)
        self.password_blank.setGeometry(QtCore.QRect(110, 70, 231, 41))
        self.password_blank.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.password_blank.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_blank.setObjectName("password_blank")
        PasswordWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PasswordWindow)
        self.statusbar.setObjectName("statusbar")
        PasswordWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PasswordWindow)
        QtCore.QMetaObject.connectSlotsByName(PasswordWindow)

    def retranslateUi(self, PasswordWindow):
        _translate = QtCore.QCoreApplication.translate
        PasswordWindow.setWindowTitle(_translate("PasswordWindow", "Password"))
        self.PasswordLabel.setText(_translate("PasswordWindow", "Input Password"))
        self.Enter_password.setText(_translate("PasswordWindow", "Enter"))
        self.label.setText(_translate("PasswordWindow", "Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PasswordWindow = QtWidgets.QMainWindow()
    ui = Ui_PasswordWindow()
    ui.setupUi(PasswordWindow)
    PasswordWindow.show()
    sys.exit(app.exec_())
